### PR TITLE
Added workaround flag to attempt to set boot override properties on settings resources for non-conformant implementations

### LINKED ISSUE #111: AMI redfish server systems's boot property is in /redfish/v1/Systems/Self/SD
AMI redfish server systems's boot property is in /redfish/v1/Systems/Self/SD

and if want to set boot property attribute, 
must send PATCH in /redfish/v1/Systems/Self/SD, not send PATCH in /redfish/v1/Systems/Self

Detail is below

/redfish/v1/Systems/Self response:
[System_Self.txt](https://github.com/DMTF/Redfish-Tacklebox/files/12168525/System_Self.txt)

/redfish/v1/Systems/Self/SD response:
[Systems_Self_SD.txt](https://github.com/DMTF/Redfish-Tacklebox/files/12168529/Systems_Self_SD.txt)

### PR DESCRIPTION
**Pull request by mraineri**
Fix #111 

@PeterKchen2 would you be able to test this fix out for me? When you run rf_boot_override.py, you'll also need to add --workaround to the command.

### CODE REVIEW

**Comment by PeterKchen2** [comment]
attached file modify is correct, ami not update boot override properties at system

[systems.zip](https://github.com/DMTF/Redfish-Tacklebox/files/12437666/systems.zip)

**Comment by mraineri** [comment]
I see what you're saying... I might want to think about adjusting this a bit since settings on a system is certainly valid for other reasons, so the warnings right now aren't 100% correct.

**Comment by mraineri** [comment]
@PeterKchen2 I've incorporated your changes plus some other modifications to it to make it a bit more dynamic with the warnings; please let me know if these updates work for you.

**Comment by PeterKchen2** [comment]
your modify will lost @Redfish.AllowableValues
[systems.zip](https://github.com/DMTF/Redfish-Tacklebox/files/12472113/systems.zip)

**Comment by mraineri** [comment]
Got it, just pushed your changes in

**Comment by mraineri** [comment]
Approved 9/15

**Pull request merged**
