### PR TITLE
#issue 106 and issue #107 implement

### PR DESCRIPTION
**Pull request by PeterKchen2**
1. run pyinstaller via setup.py support
2. PasswordChangeRequired support

### CODE REVIEW

**Comment by mraineri** [comment]
This is a bit heavy handed for what I was planning on implementing. I think it would be useful to push changes to the "login" method in the python-redfish-library project to raise a well-known exception when this message is seen so that it can be handled gracefully very early on when establishing a Redfish session. Would it be okay if I made another PR with this?

**Comment by PeterKchen2** [comment]
OK

**Comment by PeterKchen2** [comment]
Dear mraineri

does the below description about PasswordChangeRequired is correct??

1.
according to Redfish spec, when the login account's PasswordChangeRequired is true, session login should include a @message.ExtendedInfo object in the response containing the PasswordChangeRequired message from the Base Message Registry

2.
when the login account's PasswordChangeRequired is true, after session login, other redfish url requests should return 403 and
should include a @message.ExtendedInfo object in the response containing the PasswordChangeRequired message from the Base Message Registry

**Comment by PeterKchen2** [comment]
but for backend compatibility with old version python-redfish-library , I think still need check all get method response if PasswordChangeRequired message exist

**Comment by mraineri** [comment]
> Dear mraineri
> 
> does the below description about PasswordChangeRequired is correct??
> 
> 
> according to Redfish spec, when the login account's PasswordChangeRequired is true, session login should include a @message.ExtendedInfo object in the response containing the PasswordChangeRequired message from the Base Message Registry
> 
> 
> when the login account's PasswordChangeRequired is true, after session login, other redfish url requests should return 403 and should include a @message.ExtendedInfo object in the response containing the PasswordChangeRequired message from the Base Message Registry

Yes, this is all correct. But I'm thinking from a tooling perspective we can intercept this message much earlier to avoid having to implement this check everywhere. I was thinking of doing something like this in the different scripts:

```
# Set up the Redfish object
redfish_obj = redfish.redfish_client( base_url = args.rhost, username = args.user, password = args.password )
try:
    redfish_obj.login( auth = "session" )
except RedfishPasswordChangeRequiredError as e:
    print("Password change required; run rf_change_password.py to set your password")
    sys.exit(1)
except Exception as e:
    # other error
    sys.exit(1)
```

**Comment by mraineri** [comment]
> but for backend compatibility with old version python-redfish-library , I think still need check all get method response if PasswordChangeRequired message exist

That's true... We could increase the minimum version in requirements.txt though. Would that help? We've done that for other cases where new functionality in the library is required.

**Comment by PeterKchen2** [comment]
I think let is ok

**Pull request closed without merging**
