### PR TITLE
rf_raw_request.py POST/PATCH/PUT/DELETE method should set if-match header if Etag exist

### PR DESCRIPTION
**Pull request by PeterKchen2**
rf_raw_request.py POST/PATCH/PUT/DELETE method should set if-match header if Etag exist

### CODE REVIEW

**Comment by PeterKchen2** [comment]
https://github.com/DMTF/python-redfish-library/pull/146

**Comment by PeterKchen2** [comment]
after feedback, rf_raw_request.py PATCH/PUT method should set if-match header if Etag exist

**Comment by PeterKchen2** [comment]
I changed the code according to your suggestion

**Comment by mraineri** [comment]
It looks like there are a lot of other changes from other work; can the branch be pruned down to just the one change needed here?

**Comment by PeterKchen2** [comment]
https://github.com/DMTF/Redfish-Tacklebox/pull/121

**Pull request closed without merging**
